# Generated by Django 4.1.1 on 2022-10-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_rename_tag_course_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='dummy',
            field=models.BooleanField(default=False),
        ),
    ]
