# Generated by Django 4.1.1 on 2022-10-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_tag_dummy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
