# Generated by Django 4.1.1 on 2022-10-22 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_rename_name_teacher_firstname_teacher_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(blank=True, to='journal.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='Namespaces', inverse_match=True, message='Без пробілів!', regex=' ')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='Namespaces', inverse_match=True, message='Без пробілів!', regex=' ')]),
        ),
    ]
