# Generated by Django 4.1.1 on 2022-10-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students_count',
            field=models.SmallIntegerField(null=True),
        ),
    ]
