# Generated by Django 4.1.1 on 2022-10-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_student_dummy_teacher_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='Teacher',
            field=models.ManyToManyField(to='journal.teacher'),
        ),
    ]
