# Generated by Django 4.1.1 on 2022-10-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_remove_teacher_groups_group_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='Teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='group',
            field=models.ManyToManyField(to='journal.group'),
        ),
    ]
