# Generated by Django 4.1.1 on 2022-10-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_coursecategory_tag_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dummy',
            field=models.BooleanField(default=False),
        ),
    ]
