# Generated by Django 4.1.1 on 2023-01-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0018_currency_alter_teacher_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='broker',
            field=models.CharField(max_length=255),
        ),
    ]
