# Generated by Django 4.1.1 on 2023-01-25 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0018_currency_alter_teacher_title_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='last_bid_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='lot_name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
