# Generated by Django 4.1.1 on 2023-01-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0019_alter_currency_broker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
